"""Seed 12 eyebrow styles into the database."""

from sqlalchemy.orm import Session
from models.eyebrow_style import EyebrowStyle

EYEBROW_STYLES = [
    {
        "name_en": "Natural Feather",
        "name_ko": "내추럴 페더",
        "name_th": "เนเชอรัล เฟเธอร์",
        "name_vi": "Tự nhiên lông vũ",
        "description_en": "Ultra-soft hair strokes mimicking natural brow hairs.",
        "description_ko": "자연스러운 눈썹 털을 모방한 매우 부드러운 헤어 스트로크.",
        "slug": "natural-feather",
        "category": "natural",
        "difficulty": "advanced",
        "price_range_min": 300,
        "price_range_max": 600,
        "sort_order": 1,
    },
    {
        "name_en": "Ombre Powder",
        "name_ko": "옴브레 파우더",
        "name_th": "ออมเบร พาวเดอร์",
        "name_vi": "Ombre phấn",
        "description_en": "Soft gradient fill from lighter front to darker tail.",
        "description_ko": "앞쪽은 밝고 꼬리 쪽은 진한 부드러운 그라데이션 채우기.",
        "slug": "ombre-powder",
        "category": "defined",
        "difficulty": "medium",
        "price_range_min": 250,
        "price_range_max": 500,
        "sort_order": 2,
    },
    {
        "name_en": "Combination Brow",
        "name_ko": "콤비네이션 브로우",
        "name_th": "คอมบิเนชั่น บราว",
        "name_vi": "Lông mày kết hợp",
        "description_en": "Hair strokes at the front blending into powder fill toward the tail.",
        "description_ko": "앞부분은 헤어 스트로크, 꼬리 쪽은 파우더 채우기로 혼합.",
        "slug": "combination-brow",
        "category": "natural",
        "difficulty": "advanced",
        "price_range_min": 350,
        "price_range_max": 700,
        "sort_order": 3,
    },
    {
        "name_en": "Bold Arch",
        "name_ko": "볼드 아치",
        "name_th": "โบลด์ อาร์ช",
        "name_vi": "Cung đậm",
        "description_en": "High-definition bold arch for a dramatic look.",
        "description_ko": "드라마틱한 느낌의 고화질 볼드 아치형.",
        "slug": "bold-arch",
        "category": "defined",
        "difficulty": "medium",
        "price_range_min": 200,
        "price_range_max": 400,
        "sort_order": 4,
    },
    {
        "name_en": "Straight Korean Style",
        "name_ko": "스트레이트 한국형",
        "name_th": "สไตล์เกาหลีตรง",
        "name_vi": "Phong cách Hàn Quốc thẳng",
        "description_en": "Flat, straight Korean-inspired brow for a youthful look.",
        "description_ko": "젊어 보이는 납작하고 직선적인 한국식 눈썹.",
        "slug": "straight-korean",
        "category": "natural",
        "difficulty": "easy",
        "price_range_min": 200,
        "price_range_max": 450,
        "sort_order": 5,
    },
    {
        "name_en": "Micro-shading",
        "name_ko": "마이크로 쉐이딩",
        "name_th": "ไมโครเชดดิ้ง",
        "name_vi": "Tô bóng vi mô",
        "description_en": "Tiny dots creating a soft powder effect without strokes.",
        "description_ko": "스트로크 없이 부드러운 파우더 효과를 만드는 작은 점들.",
        "slug": "micro-shading",
        "category": "defined",
        "difficulty": "medium",
        "price_range_min": 250,
        "price_range_max": 500,
        "sort_order": 6,
    },
    {
        "name_en": "3D Hair Stroke",
        "name_ko": "3D 헤어 스트로크",
        "name_th": "3D เส้นผม",
        "name_vi": "Nét tóc 3D",
        "description_en": "Multi-directional strokes for ultra-realistic 3D brows.",
        "description_ko": "매우 사실적인 3D 눈썹을 위한 다방향 스트로크.",
        "slug": "3d-hair-stroke",
        "category": "feather",
        "difficulty": "advanced",
        "price_range_min": 400,
        "price_range_max": 800,
        "sort_order": 7,
    },
    {
        "name_en": "Soft Classic",
        "name_ko": "소프트 클래식",
        "name_th": "ซอฟต์คลาสสิค",
        "name_vi": "Cổ điển mềm mại",
        "description_en": "Timeless classic brow with soft fill and defined edges.",
        "description_ko": "부드러운 채우기와 선명한 윤곽의 시대를 초월한 클래식 눈썹.",
        "slug": "soft-classic",
        "category": "defined",
        "difficulty": "easy",
        "price_range_min": 150,
        "price_range_max": 350,
        "sort_order": 8,
    },
    {
        "name_en": "Nano Brow",
        "name_ko": "나노 브로우",
        "name_th": "นาโนบราว",
        "name_vi": "Lông mày nano",
        "description_en": "Machine-done nano strokes for longer-lasting realistic brows.",
        "description_ko": "기계로 시술하는 나노 스트로크로 더 오래 지속되는 사실적인 눈썹.",
        "slug": "nano-brow",
        "category": "feather",
        "difficulty": "advanced",
        "price_range_min": 500,
        "price_range_max": 900,
        "sort_order": 9,
    },
    {
        "name_en": "Fluffy Brow",
        "name_ko": "플러피 브로우",
        "name_th": "ฟลัฟฟี่บราว",
        "name_vi": "Lông mày bồng bềnh",
        "description_en": "Bushy, fluffy texture for an effortlessly full brow.",
        "description_ko": "손쉽게 풍성한 눈썹을 위한 풍성하고 보송한 질감.",
        "slug": "fluffy-brow",
        "category": "natural",
        "difficulty": "medium",
        "price_range_min": 280,
        "price_range_max": 550,
        "sort_order": 10,
    },
    {
        "name_en": "Angular Power Brow",
        "name_ko": "앵귤러 파워 브로우",
        "name_th": "แองกูลาร์ พาวเวอร์ บราว",
        "name_vi": "Lông mày góc cạnh mạnh mẽ",
        "description_en": "Sharp angles and strong definition for a bold, powerful appearance.",
        "description_ko": "대담하고 강렬한 외모를 위한 날카로운 각도와 강한 정의.",
        "slug": "angular-power-brow",
        "category": "defined",
        "difficulty": "medium",
        "price_range_min": 200,
        "price_range_max": 450,
        "sort_order": 11,
    },
    {
        "name_en": "Feather Touch",
        "name_ko": "페더 터치",
        "name_th": "เฟเธอร์ทัช",
        "name_vi": "Chạm lông vũ",
        "description_en": "Delicate feather-light strokes for the most natural finish.",
        "description_ko": "가장 자연스러운 마무리를 위한 섬세하고 가벼운 깃털 스트로크.",
        "slug": "feather-touch",
        "category": "feather",
        "difficulty": "advanced",
        "price_range_min": 380,
        "price_range_max": 750,
        "sort_order": 12,
    },
]


def seed_eyebrow_styles(db: Session) -> int:
    created = 0
    for data in EYEBROW_STYLES:
        existing = (
            db.query(EyebrowStyle).filter(EyebrowStyle.slug == data["slug"]).first()
        )
        if not existing:
            style = EyebrowStyle(**data)
            db.add(style)
            created += 1
    db.commit()
    return created
